version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: act_refugee_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped

  app:
    build: .
    container_name: act_refugee_app
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - USE_LOCAL_EMBEDDINGS=true
    volumes:
      - .:/app
    command: python main.py